<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNy1394g\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNy1394g/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNy1394g.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNy1394g\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNy1394g\appProdProjectContainer([
    'container.build_hash' => 'Ny1394g',
    'container.build_id' => '8723cf8f',
    'container.build_time' => 1614622433,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNy1394g');
